baseurl: https://r-qgis.netlify.app
copyright: Copyright © 2022, Antony Barja; all rights reserved.
paginate: 10
theme: hugo-clarity
#disqusShortname: ''
DefaultContentLanguage: es
taxonomies:
  tag: tags
